ln -sf ~/dotfiles/.config/fish/config.fish  ~/.config/fish/config.fish
ln -sf ~/dotfiles/.config/fish/config-osx.fish  ~/.config/fish/config-osx.fish
ln -sf ~/dotfiles/.config/tmux/tmux.conf ~/.config/tmux/tmux.conf
ln -sf ~/dotfiles/.config/tmux/macos.conf ~/.config/tmux/macos.conf
ln -sf ~/dotfiles/.config/tmux/utility.conf ~/.config/tmux/utility.conf
ln -sf ~/dotfiles/.config/tmux/tmux.powerline.conf ~/.counfig/tmux/tmux.powerline.conf
ln -sf ~/dotfiles/.config/fish/functions/peco_select_history.fish  ~/.config/fish/functions/peco_select_history.fish
ln -sf ~/dotfiles/.config/fish/functions/peco_select_ghq_repository.fish  ~/.config/fish/functions/peco_select_ghq_repository.fish
ln -sf ~/dotfiles/.config/nvim/init.lua  ~/.config/nvim/init.lua
ln -sf ~/dotfiles/.config/nvim/lua/chobiama/base.lua  ~/.config/nvim/lua/chobiama/base.lua
ln -sf ~/dotfiles/.config/nvim/lua/chobiama/highlights.lua  ~/.config/nvim/lua/chobiama/highlights.lua
ln -sf ~/dotfiles/.config/nvim/lua/chobiama/macos.lua  ~/.config/nvim/lua/chobiama/macos.lua
ln -sf ~/dotfiles/.config/nvim/lua/chobiama/maps.lua  ~/.config/nvim/lua/chobiama/maps.lua
ln -sf ~/dotfiles/.config/nvim/lua/chobiama/plugins.lua  ~/.config/nvim/lua/chobiama/plugins.lua
ln -sf ~/dotfiles/.config/nvim/plugin/lspconfig.lua  ~/.config/nvim/plugin/lspconfig.lua
ln -sf ~/dotfiles/.config/nvim/plugin/lspsaga.rc.lua  ~/.config/nvim/plugin/lspsaga.rc.lua
ln -sf ~/dotfiles/.config/nvim/plugin/null-ls.rc.lua  ~/.config/nvim/plugin/null-ls.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/autopairs.rc.lua  ~/.config/nvim/after/plugin/autopairs.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/bufferline.rc.lua ~/.config/nvim/after/plugin/bufferline.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/cmp.rc.lua ~/.config/nvim/after/plugin/cmp.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/colorizer.rc.lua ~/.config/nvim/after/plugin/colorizer.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/git.rc.lua ~/.config/nvim/after/plugin/git.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/gitsigns.rc.lua ~/.config/nvim/after/plugin/gitsigns.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/lsp-colors.rc.lua ~/.config/nvim/after/plugin/lsp-colors.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/lspkind.rc.lua ~/.config/nvim/after/plugin/lspkind.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/lualine.rc.lua ~/.config/nvim/after/plugin/lualine.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/mason.rc.lua ~/.config/nvim/after/plugin/mason.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/neosolarized.rc.lua ~/.config/nvim/after/plugin/neosolarized.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/prettier.rc.lua ~/.config/nvim/after/plugin/prettier.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/telescope.rc.lua ~/.config/nvim/after/plugin/telescope.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/tokyonight.rc.lua ~/.config/nvim/after/plugin/tokyonight.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/treesitter.rc.lua ~/.config/nvim/after/plugin/treesitter.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/ts-autotag.rc.lua ~/.config/nvim/after/plugin/ts-autotag.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/web-devicons.rc.lua ~/.config/nvim/after/plugin/web-devicons.rc.lua
ln -sf ~/dotfiles/.config/nvim/after/plugin/zen-mode.rc.lua ~/.config/nvim/after/plugin/zen-mode.rc.lua