ln -sf ~/ghq/github.com/chobiama/dotfiles/.config/nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/ghq/github.com/chobiama/dotfiles/.config/fish/config.fish  ~/.config/fish/config.fish
ln -sf ~/ghq/github.com/chobiama/dotfiles/.config/fish/config-osx.fish  ~/.config/fish/config-osx.fish
ln -sf ~/ghq/github.com/chobiama/dotfiles/.vim/rc/dein.toml  ~/.cache/dein/dein.toml
ln -sf ~/ghq/github.com/chobiama/dotfiles/.vim/rc/dein_lazy.toml  ~/.cache/dein/dein_lazy.toml
ln -sf ~/ghq/github.com/chobiama/dotfiles/.vimrc ~/.vimrc
ln -sf ~/ghq/github.com/chobiama/dotfiles/.config/nvim/plugins/defx.rc.vim ~/.config/nvim/plugins/defx.rc.vim
ln -sf ~/ghq/github.com/chobiama/dotfiles/.config/nvim/plugins/denite.rc.vim ~/.config/nvim/plugins/denite.rc.vim
ln -sf ~/ghq/github.com/chobiama/dotfiles/.config/nvim/plugins/coc.rc.vim ~/.config/nvim/plugins/coc.rc.vim
ln -sf ~/ghq/github.com/chobiama/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/ghq/github.com/chobiama/dotfiles/.tmux.powerline.conf ~/.tmux.powerline.conf
ln -sf ~/ghq/github.com/chobiama/dotfiles/.vimrc.lightline ~/.vimrc.lightline
