ln -sf ~/dotfiles/.config/nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/.config/fish/config.fish  ~/.config/fish/config.fish
ln -sf ~/dotfiles/.config/fish/config-osx.fish  ~/.config/fish/config-osx.fish
ln -sf ~/dotfiles/.vim/rc/dein.toml  ~/.cache/dein/dein.toml
ln -sf ~/dotfiles/.vim/rc/dein_lazy.toml  ~/.cache/dein/dein_lazy.toml
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.config/nvim/plugins/defx.rc.vim ~/.config/nvim/plugins/defx.rc.vim
ln -sf ~/dotfiles/.config/nvim/plugins/denite.rc.vim ~/.config/nvim/plugins/denite.rc.vim
ln -sf ~/dotfiles/.config/nvim/plugins/coc.rc.vim ~/.config/nvim/plugins/coc.rc.vim
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/.tmux.conf.osx ~/.tmux.conf.osx
ln -sf ~/dotfiles/.tmux.powerline.conf ~/.tmux.powerline.conf
ln -sf ~/dotfiles/.vimrc.lightline ~/.vimrc.lightline
ln -sf ~/dotfiles/.config/fish/functions/peco_select_history.fish  ~/.config/fish/functions/peco_select_history.fish
ln -sf ~/dotfiles/.config/fish/functions/peco_select_ghq_repository.fish  ~/.config/fish/functions/peco_select_ghq_repository.fish
ln -sf ~/dotfiles/.config/nvim/colors/NeoSolarized.vim ~/.config/nvim/colors/NeoSolarized.vim
